version: '2'
services:
  api:
    build: .
    command: node index.js
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "80:8080"
    environment:
      NODE_ENV: 'development'
      APP_PORT: 8080
      APP_SECRET: 'cc2017'
      MONGO_URL: mongodb://mongo/cc
    links:
      - mongo
  mongo:
    image: mongo:3.2.9
    ports:
      - "27017:27017"