version: '2'
services:
  api:
    build: .
    command: node index.js
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: 'development'
    links:
      - mongo
  mongo:
    image: mongo:3.2.9
    ports:
      - "27017:27017"